### ISSUE TITLE
Invalid mode ('wu')

### ISSUE THREAD

**Issue by joefutrelle** [joefutrelle/domdb#51]
```
domdb> search 100.0041 38 out1.csv
Traceback (most recent call last):
  File "cli.py", line 274, in <module>
    shell.cmdloop('DOMDB v1')
  File "C:\Anaconda\lib\cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "C:\Anaconda\lib\cmd.py", line 221, in onecmd
    return func(arg)
  File "cli.py", line 249, in do_search
    with open(outf,'wu') as fout:
ValueError: Invalid mode ('wu') 
```

This is occurring on Windows and so is probably Windows-specific

**Comment by joefutrelle** [comment]
First thing to try is just changing the mode back to 'w' and see if the CSV files are still usable in Windows.

**Comment by joefutrelle** [comment]
OK, that's pushed, should be ready to try now.

**Comment by KujawinskiLaboratory** [comment]
This is all set.
